worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;

    # Список серверов, куда будут проксироваться запросы.
    # Подробности по ссылке:
    # https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
    upstream backend {
        server localhost:5001;
        server localhost:5002;
    }

        server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;

	    add_header X-Served-By $upstream_addr;
            
            # Обязательные заголовки для ASP.NET Core:
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Таймауты
            proxy_connect_timeout 60s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;
        }
    }
}

    