worker_processes 1;

events {
    worker_connections 1024;
}

http {
    default_type application/octet-stream;

    upstream backend {
        server 127.0.0.1:5001;
        server 127.0.0.1:5002;

        ip_hash;
    }

        server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}

    