worker_processes 1;

events {
    worker_connections 1024;
}

http {
    default_type application/octet-stream;

    # Список серверов, куда будут проксироваться запросы.
    # Подробности по ссылке:
    # https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
    upstream backend {
        server localhost:5001;
        server localhost:5002;
    }

        server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
        }
    }
}

    